### ISSUE TITLE
Gợi ý giảm flickering màn hình

### ISSUE THREAD

**Issue by UIT-21522825** [UIT-21520378/SS004.M16.CLC-SNAKE_GAME#12]
Khi chạy game, màn hình bị flicker nhiều bởi vì sau mỗi lần chạy phải gọi hàm cls() hoặc lệnh system("cls") để xóa phần đuôi con rắn sau khi nó di chuyển sang vị trí khác.
Tui nghĩ sẽ được hơn nếu thay vì làm vậy thì mình có thể gotoxy(x đuôi ban đầu, y đuôi ban đầu) để std::cout << ' ' thì như thế sẽ có thể xóa được đuôi con rắn.
Mọi người xem thử làm như thế nào được không? Tui thử rồi nhưng không thành công.

**Comment by UIT-21520378** [comment]
@hatrontai phần này Tài làm được không ?

**Comment by UIT-21520378** [comment]
Tui nghĩ thế thì mình chỉ cần vẽ ra con rắn gốc, rồi chia làm hai trường hợp là không ăn quả mà cứ để con rắn đi (thì mình chỉ cần cout đâu con rắn và cout << "" ở đuôi con rắn là được) và trường hợp ăn quả + tăng độ dài thì hơi phức tạp hơn nhưng nếu xét logic thì game sẽ đỡ bị flicker rất nhiều

**Comment by UIT-21520378** [comment]
@UIT-21520373 Làm được không ?

**Comment by UIT-21520378** [comment]
Nếu chỉ dùng gotoxy() để thực hiện xóa và vẽ con rắn thì có nhanh hơn cls không nhỉ ?

**Comment by UIT-21520378** [comment]
@UIT-21520373 Làm được không ?
